import { defineModel } from 'skedyul'

export default defineModel({
  handle: 'google_calendar',
  label: 'Google Calendar',
  labelPlural: 'Google Calendars',
  labelTemplate: '{{ summary }}',
  description: 'Linked Google Calendar with sync settings and watch channel state',
  scope: 'internal',

  fields: [
    {
      handle: 'calendar_id',
      label: 'Calendar ID',
      type: 'string',
      requirement: 'required',
      system: true,
      description: 'Google Calendar ID',
      owner: 'app',
    },
    {
      handle: 'summary',
      label: 'Summary',
      type: 'string',
      requirement: 'optional',
      system: true,
      description: 'Calendar display name',
      owner: 'app',
    },
    {
      handle: 'primary',
      label: 'Primary Calendar',
      type: 'boolean',
      requirement: 'optional',
      system: true,
      default: false,
      description: 'Whether this is the primary calendar for the connected account',
      owner: 'app',
    },
    {
      handle: 'sync_enabled',
      label: 'Sync Enabled',
      type: 'boolean',
      requirement: 'optional',
      system: true,
      default: false,
      description: 'Whether calendar sync is active',
      owner: 'app',
    },
    {
      handle: 'sync_direction',
      label: 'Sync Direction',
      type: 'string',
      requirement: 'optional',
      system: true,
      default: 'both',
      description: 'Sync direction for this calendar',
      owner: 'app',
      definition: {
        limitChoices: 1,
        options: [
          { label: 'Push to Google', value: 'push', color: 'blue' },
          { label: 'Pull from Google', value: 'pull', color: 'green' },
          { label: 'Two-way', value: 'both', color: 'purple' },
        ],
      },
    },
    {
      handle: 'external_read_only',
      label: 'External Read Only',
      type: 'boolean',
      requirement: 'optional',
      system: true,
      default: true,
      description: 'When true, block write tools from modifying Google events',
      owner: 'app',
    },
    {
      handle: 'sync_token',
      label: 'Sync Token',
      type: 'string',
      requirement: 'optional',
      system: true,
      description: 'Google incremental sync token',
      owner: 'app',
    },
    {
      handle: 'watch_channel_id',
      label: 'Watch Channel ID',
      type: 'string',
      requirement: 'optional',
      system: true,
      description: 'Google push notification channel ID',
      owner: 'app',
    },
    {
      handle: 'watch_resource_id',
      label: 'Watch Resource ID',
      type: 'string',
      requirement: 'optional',
      system: true,
      description: 'Google push notification resource ID',
      owner: 'app',
    },
    {
      handle: 'watch_expiration',
      label: 'Watch Expiration',
      type: 'datetime',
      requirement: 'optional',
      system: true,
      description: 'When the Google push watch channel expires',
      owner: 'app',
    },
    {
      handle: 'watch_token',
      label: 'Watch Token',
      type: 'string',
      requirement: 'optional',
      system: true,
      description: 'Secret token used to validate Google push notifications',
      owner: 'app',
    },
    {
      handle: 'last_synced_at',
      label: 'Last Synced At',
      type: 'datetime',
      requirement: 'optional',
      system: true,
      description: 'Timestamp of the last successful sync',
      owner: 'app',
    },
  ],
})
