/**
 * Official REA Leads API enquiry `type` values.
 * https://partner.realestate.com.au/leads/overview/
 *
 * Stored as the raw REA enum so enquiry AppCrmMap identity-maps into CRM.
 * Labels are for CRM select options and the map editor.
 */

export const REA_ENQUIRY_TYPES = {
  REALESTATE_COM_AU_LISTING: 'REALESTATE_COM_AU_LISTING',
  REALESTATE_COM_AU_RENT: 'REALESTATE_COM_AU_RENT',
  REALESTATE_COM_AU_AGENCY: 'REALESTATE_COM_AU_AGENCY',
  REALESTATE_COM_AU_AGENT: 'REALESTATE_COM_AU_AGENT',
  REALESTATE_COM_AU_LEAD_AD: 'REALESTATE_COM_AU_LEAD_AD',
  REALESTATE_COM_AU_SALES_APPRAISAL_REQUEST:
    'REALESTATE_COM_AU_SALES_APPRAISAL_REQUEST',
  REALESTATE_COM_AU_RENTAL_APPRAISAL_REQUEST:
    'REALESTATE_COM_AU_RENTAL_APPRAISAL_REQUEST',
  REALESTATE_COM_AU_AGENCY_SALES_APPRAISAL_REQUEST:
    'REALESTATE_COM_AU_AGENCY_SALES_APPRAISAL_REQUEST',
  REALESTATE_COM_AU_AGENCY_RENTAL_APPRAISAL_REQUEST:
    'REALESTATE_COM_AU_AGENCY_RENTAL_APPRAISAL_REQUEST',
  REALCOMMERCIAL_COM_AU_BUY: 'REALCOMMERCIAL_COM_AU_BUY',
  REALCOMMERCIAL_COM_AU_LEASE: 'REALCOMMERCIAL_COM_AU_LEASE',
  REALCOMMERCIAL_COM_AU_BUY_AND_LEASE: 'REALCOMMERCIAL_COM_AU_BUY_AND_LEASE',
  REALCOMMERCIAL_COM_AU_FIND_AGENCY: 'REALCOMMERCIAL_COM_AU_FIND_AGENCY',
  REALCOMMERCIAL_COM_AU_DOCUMENT_ACCESS: 'REALCOMMERCIAL_COM_AU_DOCUMENT_ACCESS',
  DEVELOPER_PROJECT: 'DEVELOPER_PROJECT',
  DEVELOPER_PROJECT_DOCUMENT_DOWNLOAD: 'DEVELOPER_PROJECT_DOCUMENT_DOWNLOAD',
  DEVELOPER_BUILDER_GENERAL: 'DEVELOPER_BUILDER_GENERAL',
  DEVELOPER_BUILDER_INFORMATION_PACK: 'DEVELOPER_BUILDER_INFORMATION_PACK',
  DEVELOPER_BUILDER_DESIGN: 'DEVELOPER_BUILDER_DESIGN',
  DEVELOPER_BUILDER_PROMOTION: 'DEVELOPER_BUILDER_PROMOTION',
  DEVELOPER_BUILDER_DISPLAY_VISIT: 'DEVELOPER_BUILDER_DISPLAY_VISIT',
  DEVELOPER_INSPECTION_REGISTRATION: 'DEVELOPER_INSPECTION_REGISTRATION',
  DEVELOPER_EXTENSION_CAMPAIGN: 'DEVELOPER_EXTENSION_CAMPAIGN',
  OTHER: 'OTHER',
} as const

export type ReaEnquiryType =
  (typeof REA_ENQUIRY_TYPES)[keyof typeof REA_ENQUIRY_TYPES]

export const REA_ENQUIRY_TYPE_LABELS: Record<ReaEnquiryType, string> = {
  REALESTATE_COM_AU_LISTING: 'Residential listing',
  REALESTATE_COM_AU_RENT: 'Rental listing',
  REALESTATE_COM_AU_AGENCY: 'Find an agency',
  REALESTATE_COM_AU_AGENT: 'Find an agent',
  REALESTATE_COM_AU_LEAD_AD: 'Lead ad',
  REALESTATE_COM_AU_SALES_APPRAISAL_REQUEST: 'Sales appraisal (agent)',
  REALESTATE_COM_AU_RENTAL_APPRAISAL_REQUEST: 'Rental appraisal (agent)',
  REALESTATE_COM_AU_AGENCY_SALES_APPRAISAL_REQUEST: 'Sales appraisal (agency)',
  REALESTATE_COM_AU_AGENCY_RENTAL_APPRAISAL_REQUEST: 'Rental appraisal (agency)',
  REALCOMMERCIAL_COM_AU_BUY: 'Commercial buy listing',
  REALCOMMERCIAL_COM_AU_LEASE: 'Commercial lease listing',
  REALCOMMERCIAL_COM_AU_BUY_AND_LEASE: 'Commercial buy and lease listing',
  REALCOMMERCIAL_COM_AU_FIND_AGENCY: 'Commercial find an agency',
  REALCOMMERCIAL_COM_AU_DOCUMENT_ACCESS: 'Commercial document download',
  DEVELOPER_PROJECT: 'Developer project',
  DEVELOPER_PROJECT_DOCUMENT_DOWNLOAD: 'Developer project documents',
  DEVELOPER_BUILDER_GENERAL: 'Builder profile',
  DEVELOPER_BUILDER_INFORMATION_PACK: 'Builder information pack',
  DEVELOPER_BUILDER_DESIGN: 'Builder design',
  DEVELOPER_BUILDER_PROMOTION: 'Builder promotion',
  DEVELOPER_BUILDER_DISPLAY_VISIT: 'Builder display visit',
  DEVELOPER_INSPECTION_REGISTRATION: 'Inspection registration',
  DEVELOPER_EXTENSION_CAMPAIGN: 'Developer campaign',
  OTHER: 'Other',
}

export const REA_ENQUIRY_TYPE_OPTIONS: Array<{
  value: ReaEnquiryType
  label: string
}> = (
  Object.entries(REA_ENQUIRY_TYPE_LABELS) as Array<[ReaEnquiryType, string]>
).map(([value, label]) => ({ value, label }))
